### ISSUE TITLE
update existing qa and dev indices setting to the new shard setting

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/donor-submission-aggregator#108]
The problem: recently we updated the default es index settings in this ticket: https://github.com/icgc-argo/donor-submission-aggregator/issues/54, this resulted in rollcall unable to clone existing indices because of the mismatch in es settings, as es only allows index clone when old and new index have the same settings. 

old index with `number_of_shards = 1, numer_of_replicas=  1`:
![image.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/4115027e-0b26-4b3a-b948-f7658ff3e862)

new index settings:
![image.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/f5482d4a-292b-45d0-b6cc-0569d9814c59)

Expected results:
all donor-aggregator indices in qa and dev should be updated to new settings: 
```
"settings": {
    "index.number_of_shards": 3,
    "index.number_of_replicas": 2
  }
```
Possible Solution: 
1. Manually update indices settings using es `PUT /_settings` endpoint
- can only update number_of_replicas not number_of_shards
2. change aggregator rollcall `CreateResolvableIndexRequest`request to `cloneFromReleasedIndex = false` which disables clone
3. ?

**Comment by rosibaj** [comment]
@Buwujiu  was there a PR to attach here?

**Comment by Buwujiu** [comment]
https://github.com/icgc-argo/donor-submission-aggregator/pull/99
