### ISSUE TITLE
Investigate expired jwt 

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/donor-submission-aggregator#119]
- Dev donor aggregator logged a rdpc token expired error on Jan.4 after holiday break, this is not the expected behaviour as aggregator should automatically get a new jwt token from ego when previous token expires. 
- Possible cause is unknown yet, in order to investigate, an expired jwt token is needed, but as dev aggregator is pointing to prod ego and ego private key is not accessible, we cannot manually generate tokens. 
- Investigation should continue once aggregator points to dev/qa ego. 
- This can be done as a unit test. write test for aggregator side.

**Comment by joneubank** [comment]
I connected a PR https://github.com/icgc-argo/donor-submission-aggregator/pull/173 but I am not seeing it in this ticket so here is a link.
