### ISSUE TITLE
Update fetch analyses graphql query

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/donor-submission-aggregator#130]
A new change has been made to rdpc gateway api which involves api structure change: https://github.com/icgc-argo/rdpc-gateway/issues/58#issuecomment-762360449,  in order to be compatible with the latest api, donor aggregator query needs to be updated.

**Comment by rosibaj** [comment]
@Buwujiu can you please add a version to this ticket to indicate what version this change represents?

**Comment by rosibaj** [comment]
Tested on RDPC API and with dashboard runs. The changes to respond to the response format are available and working.
