### ISSUE TITLE
Mutect 2: Mapping Update

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/donor-submission-aggregator#150]
- Update ES Mapping to include the fields needed for Mutect2
- There should be three fields for each of the running states. (running/complete/error)
- Possibly need to migrate indices to new mapping since we are adding fields?

**Comment by Buwujiu** [comment]
Tested in argo dev, I did the following:
1. indexed PACA-CA using donor aggregator swagger index-program endpoint
2. checked the mapping of the latest es index `donor_centric_program_pacaca_re_37` in Kibana: 
`GET /donor_centric_program_pacaca_re_37/_mapping
`
new mutect fields are present in the mapping: 
```
        "mutectCompleted" : {
          "type" : "byte"
        },
        "mutectFailed" : {
          "type" : "byte"
        },
        "mutectRunning" : {
          "type" : "byte"
        },
```

**Comment by rosibaj** [comment]
working as expected all the way up to gateway/ui.  LGTM.  no bugs found!  thanks @Buwujiu !
