### ISSUE TITLE
🐛 Donor Dashboard Event Indexing: Is it working? 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/donor-submission-aggregator#176]
## Describe the bug
I was looking at the dashboard for another reason, but noticed some data anomalies. 

## Steps To Reproduce

1. Go to https://platform.icgc-argo.org/submission/program/OCCAMS-GB/dashboard
2. Sort the `Sanger VC column descending`
3. Set page size of the table to 100.  Go to Page 2. 
4. Search for donor: `DO234422`.  On the dashboard you can see the have 1 in progress Sanger, and 1 in progress Mutect 2: 
![image](https://user-images.githubusercontent.com/15824252/112888081-eae5df80-90a1-11eb-8783-454ec306c6a1.png)
5.  I noticed there were a lot of in progress in this section; more than we ever have concurrently running. So i decided to check if this donor had any published analyses that correspond to the Sanger VC.  I did that with this query:
```
query test_num_in_dash {
  analyses(
    filter: {
      donorId: "DO234422"
      analysisState: PUBLISHED
      analysisType: "variant_calling"
      #analysisId: "8ebe3a61-e06c-4616-be3a-61e06ca616ce"
    }
  ) {
    info{
      totalHits
    }
    content {
      analysisId
      analysisState
      analysisType
      #analysisVersion
      updatedAt
      firstPublishedAt
      studyId
      experiment
      donors {
        # donorId
        # submitterDonorId
        specimens {
          # specimenId
          # submitterSpecimenId
          tumourNormalDesignation
      #     samples {
      #       sampleId
      #       submitterSampleId
      #       matchedNormalSubmitterSampleId
      #     }
         }
       }
      repositories{
        code
      }
      files {
        dataType
      }
      inputForRuns {
        runId
        state
      }
      workflow{
        runId
        run{
          runId
          state
          startTime
          completeTime
        }
        inputs
      }
    }
  }
}
````

You can see there the run that generated these is listed as COMPLTED on sanger for runid `wes-1e647943c32e4f6a92a2b0d62631ec22`

Looking at the epoch time in the results, I can see it was completed a few days ago:
Completed Sunday March 9, 2021: 
![image](https://user-images.githubusercontent.com/15824252/112888292-2bddf400-90a2-11eb-97fe-1311e3b6c849.png)

## Expected behaviour
This should show a completed run.

**Comment by rosibaj** [comment]
Test with @joneubank.  In production environment: 
- clinical events are successfully being read by platform kafka
- song publish events are `not` being delivered to the platform kafka. 
-- @rosibaj published, unpublished, and suppressed an analysis and no events were observed by @joneubank.  The aggregator did not initiate as it did not receive events. 
 
Tested in teh QA environment: 
- song publish events were received to expected topic, for publish unpublish and suppress
-

**Comment by rosibaj** [comment]
Possible followup: https://github.com/icgc-argo/rdpc-infra/issues/175

**Comment by joneubank** [comment]
https://github.com/OICR/argo-infra/blob/master/helm/donor-submission-aggregator/prod/values.yaml#L16

Feature flag is not enabled.

**Comment by rosibaj** [comment]
- `kship-staging` added to `prod rdp`c to ship `prod song` events to staging. this allows us to see everything publish in file repository still. 
- `kship-prod` events verified to be communicating with `prod platform api` and dashboard correctly responding to PUBLISHED events.  Bug logged for https://github.com/icgc-argo/donor-submission-aggregator/issues/178  .  `prod maestro` is NOT enabled (running, but listening to FAKE kafka topics so it will not receive song-analysis events) for event indexing.   IF somethign is published, the index is not aliased so its ye;lling into the void.
