### ISSUE TITLE
Design: Donor releaseStatus property is not being populated

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/donor-submission-aggregator#209]
All donors being given releaseStatus of NO_RELEASE by default. The value of this property needs to be determined based on file statuses as stated by the `files-service`

## Detailed Description

End goal is to have the releaseStatus of every donor reflect the release_state of their files. The logic should be (@rosibaj to confirm):
`NO_RELEASE` - all files for donor have `release_state` of `RESTRICTED` or `QUEUED`
`FULLY_RELEASED` - all files for donor have `release_state` of `PUBLIC`
`PARTIALLY_RELEASED` - a mix of `PUBLIC` and `RESTRICTED` or `QUEUED` amongst their files. Use this if neither of the other two conditions apply

The data for this should be read from the `files-service` by querying for all files for a donor and confirming the `release_state` of those files.

This is needed to populate the donor summary indices to properly show release state per donor on the program submission dashboard.

## Possible Implementation

Some changes may be needed to files-service to support this. Need to confirm ability to query by donor ID for list fo files. This would allow a manual check whenever a donor is being updated.

In order to keep the donor index up to date with file release changes, we should also implement notifications from files-service to donor aggregator through kafka. Files-service can publish notifications to a kafka topic when a file release_state is changed, and the donor aggregator can listen for these notifications and update donors as necessary.

## Closing Criteria
Wikipage

**Comment by rosibaj** [comment]
1. Update files-service to serve data based on DONOR_ID 
- https://github.com/icgc-argo/files-service/issues/70 
- https://github.com/icgc-argo/files-service/issues/71

2. Update donor dashboard aggregator to read from the above endpoints 
- https://github.com/icgc-argo/donor-submission-aggregator/issues/215

3. After any release, we need to update a donors releaseStatus.  The file-service needs to publish an event to Kafka to notify of updates. 
- https://github.com/icgc-argo/files-service/issues/72

4. Dashboard should respond do Kafka events from file-service for release information
