### ISSUE TITLE
Add Open Access WF  logic to the aggregator to populate index 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/donor-submission-aggregator#219]
Add Open Access WF  logic to the aggregator to populate index  to support  https://github.com/icgc-argo/platform-ui/issues/2063

- [x] Update the ES mapping with new field(s). Example of the fields that need to be added fro a workflow type. 
![image](https://user-images.githubusercontent.com/15824252/134539326-9c8e9f3b-dbc4-415d-bf17-45781a4fa8a5.png)
- [x] Update the login in aggregator to populate index with values based on the ef `https://github.com/icgc-argo-workflows/open-access-variant-filtering` 
- [x] Make sure aggregates for chart work (e.g. https://github.com/icgc-argo/donor-submission-aggregator/issues/162)

**Comment by kcullion** [comment]
moved this to QA as the issues with the Program Dashboard aren't related to the open access workflow.

**Comment by kcullion** [comment]
working as expected in staging!!
