### ISSUE TITLE
Populate 2 RNA Raw Reads ES Fields 

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/donor-submission-aggregator#236]
## Requirement:
Populate 2 new ES fields to support RNA-seq Raw Reads status count.

![image.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/c21a7c7a-7149-4a37-9c69-961524f543d1)

The added fields can be called: 
`publishedRNANormalAnalysis`
`publishedRNATumourAnalysis`

## Possible Implementation:
- [ ] Add new fields to the ES mapping.
- [ ] update aggregator to populate these new fields. 
- [ ] query rdpc api to get analyses that meet these criteria: 
```
"analysisState": "PUBLISHED",
"analysisType": "sequencing_experiment",
"experimental_strategy": "RNA-Seq",
```

**Comment by Buwujiu** [comment]
This ticket is done under PR: https://github.com/icgc-argo/donor-submission-aggregator/pull/255.
Tested in QA with APGI-AU and TCRB-CA. working as expected.
