### ISSUE TITLE
Bug: DNA Raw Reads Numbers Showing both DNA and RNA 

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/donor-submission-aggregator#241]
## Issue Description: 
With the RNA pipeline data coming in, QA program TCRB-CA dashboard raw reads column is showing mixed data. There are currently 2 normal seq exp analyses, 2 tumour seq exp analyses, and 1 RNA tumour sample in rdpc qa. The RNA analysis id is 146be53f-caa2-4799-abe5-3fcaa2a799da. Since donor aggregator does not differentiate RNA from DNA, this column is showing a combination of both. However there is 1 RNA sample and 4 DNA samples. 

![Screen Shot 2022-02-07 at 3.38.07 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/f0595d3e-ea83-4946-a8e6-699a74c6e5f5)

## How to Reproduce
go to donor dashboard: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/TCRB-CA/dashboard, look for donor `DO262483`. 

## Expected Results
As shown in the screenshot, the correct raw reads number should be 2N, 2T. 
The ES fields responsible for the raw reads column are : `publishedNormalAnalysis` and `publishedTumourAnalysis`.
use  "experimental_strategy": "RNA-Seq" to differentiate RNA from DNA.

**Comment by kcullion** [comment]
@Buwujiu @lindaxiang I'm wondering why the registered samples isn't 2N (it's 1N)? Wouldn't both normal samples have to be registered first?

Linda can you please help test this ticket in QA?

**Comment by lindaxiang** [comment]
@kcullion 
The donor has 1N DNA + 1T DNA + 1T RNA registered samples
1N DNA has both WGS + WXS Raw reads submitted
1T DNA has both WGS + WXS Raw reads submitted
1T RNA has Raw reads submitted
I can see the `Raw reads` are expected: 2N + 2T
![Screen Shot 2022-04-13 at 2 17 33 PM](https://user-images.githubusercontent.com/7522294/163244785-450425b9-c71d-406e-afd5-a83672994ab6.png)

@Buwujiu did you separate RNA and DNA samples already?

**Comment by kcullion** [comment]
thanks for confirming @lindaxiang !

**Comment by Buwujiu** [comment]
@lindaxiang No I have not separated the RNA and DNA samples yet, right now it's showing both samples as DNA. this ticket only separates RNA and DNA raw reads.

**Comment by b-f-chan** [comment]
@Buwujiu @lindaxiang - Do we still need to separate the RNA and DNA samples?  What do we need in order to move this ticket along to ready for release?

**Comment by Buwujiu** [comment]
@b-f-chan yes, there is another ticket to separate RNA and DNA samples, we can move this to awaiting release if Linda approves.
