### ISSUE TITLE
Add RNA Alignment Status Fields to ES

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/donor-submission-aggregator#242]
## Requirement: 
Populate the following 3 ES fields to support RNA alignment WF status: 
`RNAalignmentsCompleted`,
`RNAalignmentsRunning`,
`RNAalignmentsFailed`.

## Possible Implementation: 
- [ ] Update ES mapping and add new fields 
- [ ]  Query RDPC gateway API to get RNA alignment wf data, using "workflowRepoUrl": "https://github.com/icgc-argo-workflows/rna-seq-alignment.git" as filter. 
- [ ] Convert RDPC data and count the number of alignment status for each donor.

**Comment by b-f-chan** [comment]
@lindaxiang to test

**Comment by lindaxiang** [comment]
@b-f-chan I can confirm that three new rna alignment status fields have been added:
- rnaAlignmentsCompleted
- rnaAlignmentsRunning
- rnaAlignmentFailed
Good job @Buwujiu

**Comment by Buwujiu** [comment]
Removed `feature-hidden` label as no feature flag was added.
