### ISSUE TITLE
Add RNA raw reads firstPublishedDate, alignment firstPublishedDate fields to ES

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/donor-submission-aggregator#245]
## Requirement
In order to represent the number of donor's RNA molecular data submission progress, we need to provide two ES fields for the gateway API: 
`RNARawReadsFirstPublishedDate`,
`RNAAlignmentFirstPublishedDate`.

`RNARawReadsFirstPublishedDate` is the earliest date when a RNA sample(regardless of normal or tumour) is published in song. The date is populated by the field `firstPublishedAt` in rdpc api. 

`RNAAlignmentFirstPublishedDate` is the earliest date when a `sequencing_alignment` analysis with `experimental_strategy` = `RNA-Seq` is published. 

Refer to `2.4.2 Molecular Data Source Data` in wiki: https://wiki.oicr.on.ca/display/icgcargotech/Program+Dashboard+Page+Specs

## Possible Implementation
- [ ] Add `RNARawReadsFirstPublishedDate`, `RNAAlignmentFirstPublishedDate` to ES mapping.
- [ ] Populate these fields by querying data from rdpc api.

**Comment by Buwujiu** [comment]
> Found some old repository URLs, need to integrate with new ones @Buwujiu will create separate ticket to track

Turns out we don't need new tickets after all. There is fuzzy search in rdpc api that handles both old and new urls.

**Comment by lindaxiang** [comment]
@Buwujiu just checked the `donor_centric_program` ES indices in QA, the above fields were added.

**Comment by edsu7** [comment]
@Buwujiu , can confirm that`rnaAlignmentFirstPublishedDate` and `rnaRawReadsFirstPublishedDate` found in `donor_centric_program_apgiau_re_2067`

**Comment by Buwujiu** [comment]
Removed `feature-hidden` label as no feature flag was added.
