### ISSUE TITLE
Populate 2 fields for RNA Registered Samples Columns

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/donor-submission-aggregator#253]
## Requirements:
In order to support the RNA Registered Samples columns, add 2  new ES fields to capture the number of tumour and normal RNA samples. 

![image.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/cb3aa97d-23b4-4633-8fc1-53aef71fc75f)

## Possible Implementation: 
- [ ] The new fields could be named: `registeredRNANormalSamples`, `registeredRNATumoutSamples`.
- [ ] query sample data from clinical and count the RNA samples for donors.

**Comment by lindaxiang** [comment]
@b-f-chan I can confirm two fields have been added:
- rnaRegisteredNormalSamples
- rnaRegisteredTumourSamples
The numbers look correct to me.

**Comment by Buwujiu** [comment]
Removed `feature-hidden` label as no feature flag was added.
