### ISSUE TITLE
API to provide the number of matched T/N raw reads DNA pairs for donor

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/donor-submission-aggregator#254]
In order to support dashboard UI -
1.  DNA raw reads columns display correct error and tooltips, 
2. DNA raw reads filters. 
3. Donors with matched T | N pairs progress card. 

API must provide the number of matched T/N raw reads DNA pairs for donors. 

T’s matchedNormalSubmitterSampleId = N’ sample id
AND
T’ experimental_strategy must = N’ experimental_strategy

Expected data example:

DO1: [a1 - T, a2 - N]  WXS
         [a1 - T, a3 - N]  WXS
         [a4 - T, a5 - N] WGX
the matchedParis = 3.

DO2 : a1 - T, WGS, a2 - T WGS,
         a3 - N, WXS, a4 - N WXS,
the matched pairs = 0.

implement in rdpc gateway or donor aggregator??

**Comment by b-f-chan** [comment]
Purely backend, @Buwujiu will test herself

**Comment by Buwujiu** [comment]
tested in QA on ROSI-RU, RDPCDEV-CA, TCRB-CA, working as expected.
