### ISSUE TITLE
Update Rollcall version in ARGO

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/donor-submission-aggregator#30]
Changes being made in Rollcall here for vault support:  https://github.com/overture-stack/rollcall/issues/25

- [x] Upgrade the Rollcall version in ARGO
- [x] Modify the chart 
- [x] Update the configuration of the environment variables & vault policy

Make sure Rollcall is pointed to the NEW Elasticsearch as part of this configuration

**Comment by hlminh2000** [comment]
Rollcall required some minor updates to work with the new elasticsearch (https). Once this in QA, feature can be tested end-to-end (up to elasticsearch)

**Comment by jaserud** [comment]
rollcall code chagnes: https://github.com/overture-stack/rollcall/issues/25
