### ISSUE TITLE
Specify shard count on index creation

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/donor-submission-aggregator#54]
Currently all the index created are going on one shard. We might want to increase this for better workload distribution

Set the default to 3 

## Detailed Description
Shards allow distribution of workload across cluster node. Multiple shards will prevent big programs from putting stress on one ES node.

## Possible Implementation
Rollcall has a feature to accept index setting for index creation. We should pass something there. @jaserud  has more info for rollcall.

**Comment by rosibaj** [comment]
@hlminh2000 will this also need to come with a reindexing task for all current exisint donor-aggregation indices?

**Comment by hlminh2000** [comment]
@rosibaj technically yes, but since the indices are likely going to be recomputed very often given we're pretty early in the project, it might not be necessary.

**Comment by Buwujiu** [comment]
In order to set shard settings upon index creation, aggregator will call rollcall's /indices/create endpoint to pass desired shard settings,  I found a bug in rollcall where index settings are not being used correctly, will fix rollcall first.
