### ISSUE TITLE
Update indexing method to also read data during upsert

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/donor-submission-aggregator#55]
Current there is no read step in the indexing. For future indexing steps, we need to have the indexing flow be this:

1) clone current program index
2) read documents of interest in the clone 
3) complete aggregation updates to merge data 
4) upsert to cloned index
5) swap index out to newly done data 

## Exit Criteria 
Update aggregator and have it working the same as it currently does, but with the new format.

**Comment by rosibaj** [comment]
@wajiha-oicr @hlminh2000 any way to get this to QA today?

**Comment by wajiha-oicr** [comment]
> @wajiha-oicr @hlminh2000 any way to get this to QA today?

Just put this PR up! https://github.com/icgc-argo/donor-submission-aggregator/pull/77
I assumed it was going to be tested in dev (oops!), sorry that's my mistake!
