### ISSUE TITLE
aggregate source events into a single topic

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/donor-submission-aggregator#60]
As we expand the aggregator to handle multiple topics, we need to maintain proper processing queue for events that relate to the same programs.

## Detailed Description
basically implement the Kafka event aggregation design here: https://drive.google.com/file/d/1dAJL7yre96sxA0WWMLklAujp-xCeJ_-O/view?usp=sharing
- Also refactor the current flow to be specifically for Clinical data to make space for integrating RDPC event processing.
- Include tests!

**Comment by hlminh2000** [comment]
if the aggregator is working normally as usual, then everything is good!

**Comment by rosibaj** [comment]
nothing abnormal observed!
