### ISSUE TITLE
ETL Sanger Numbers to Donor Aggregation Index

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/donor-submission-aggregator#79]
- [ ] Create the query to the RDPC for sanger-analyses (behind feature flag) 
- [ ] Transform data to donor centric view
--- new step in transform to count unique T/N pairs 
- [ ] Fill in the donor mapping with RDPC data that was transformed (for sanger only)

Take the query from the the RDPC and transform the data into the needed shape

## Expected Outcome 
- [ ] Can query for the numbers from the API for sanger-analyses
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/19441446-ace9-4fbf-85ec-3aa587028b74) 
- [ ] Has a feature flag to TURN OFF for production deploy

**Comment by Buwujiu** [comment]
Note  to myself: once ticket https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/icgc-argo/rdpc-gateway/48 is done, add filter to query.
